// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetPlatform.Data;

namespace VetPlatform.Data.Migrations.VetPlatform
{
    [DbContext(typeof(VetPlatformContext))]
    partial class VetPlatformContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VetPlatform.Data.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Schedule");

                    b.Property<string>("Status");

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("19458668-177c-4ca8-9acb-6cd2da85903f"),
                            Schedule = new DateTime(2019, 4, 20, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = new Guid("37ef41bd-b7ed-4fa2-bef8-916b03b1e174")
                        },
                        new
                        {
                            Id = new Guid("5d1f7f02-c4e8-40c5-acff-2f9fc76868fc"),
                            Schedule = new DateTime(2019, 4, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = new Guid("37ef41bd-b7ed-4fa2-bef8-916b03b1e174")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
